### ISSUE TITLE
WAMC Installation Error

### ISSUE THREAD

**Issue by tnchristo** [ibm-datapower/appliance-management-center#10]
Hey,
I'm trying to build AMT with mvn -e -X install, but I'm getting the error:
-----------------------------------------------------------------------------------------------------------------
[DEBUG] looking for resolver catalog at D:\WAMC\appliance-management-toolkit-master\src\main\catalog\resolver-catalog.xml
java.io.IOException: Cannot run program "D:\WAMC\appliance-management-toolkit-master\javac": CreateProcess error=2, The system cannot find the file specified
java.io.IOException: CreateProcess error=2, The system cannot find the file specified
java.io.IOException: Cannot run program "D:\WAMC\appliance-management-toolkit-master\javac": CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at org.apache.xmlbeans.impl.tool.CodeGenUtil.externalCompile(CodeGenUtil.java:231)
        at org.apache.xmlbeans.impl.tool.SchemaCompiler.compile(SchemaCompiler.java:1154)
        at org.codehaus.mojo.xmlbeans.AbstractXmlBeansPlugin.execute(AbstractXmlBeansPlugin.java:280)
        at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:207)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
        at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:116)
        at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:80)
        at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
        at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:307)
        at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:193)
        at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:106)
        at org.apache.maven.cli.MavenCli.execute(MavenCli.java:863)
        at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:288)
        at org.apache.maven.cli.MavenCli.main(MavenCli.java:199)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: java.io.IOException: CreateProcess error=2, The system cannot find the file specified
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
-------------------------------------------------------------------------------------------------------------------
Please help. I have checked, and rechecked my system, but can't find anything wrong.

Thanks

**Comment by fmoraes74** [comment]
Do you have the Java compiler installed and JAVA_HOME is pointing to the install directory of the SDK?

Also, check if this helps out: https://stackoverflow.com/questions/18957486/ioexception-cannot-run-program-javac-createprocess-error-2-the-system-canno

**Comment by tnchristo** [comment]
java (jre1.8.0_45) is installed and JAVA_HOME points to it. Two things that don't make any sense 
1)Why this "D:\WAMC\appliance-management-toolkit-master\src\main\catalog\resolver-catalog.xml" when there is no such folder

2)Why trying to run javac from WAMC location: java.io.IOException: Cannot run program "D:\WAMC\appliance-management-toolkit-master\javac": CreateProcess error=2, The system cannot find the file specified

Thanks

**Comment by fmoraes74** [comment]
You need a JDK not a JRE. Can you confirm that you `javac` installed to compile java code? The AMT code depends on `xmlbeans` which is what causes those issues.
