### ISSUE TITLE
error when uploading firmware to the repository

### ISSUE THREAD

**Issue by tomvanoppens** [ibm-datapower/appliance-management-center#3]
When you upload new firmware it gets to 99% and the window closes.
In the history the action details has started and submitted.

WARNING: WAMT0094E: An unexpected error occurred. The system might not be stable.
java.lang.OutOfMemoryError: Java heap space
        at com.ibm.datapower.amt.clientAPI.Blob.getBase64Encoded(Blob.java:430)
        at com.ibm.datapower.amt.clientAPI.FirmwareVersion.<init>(FirmwareVersion.java:181)
        at com.ibm.datapower.amt.clientAPI.AddFirmwareTask.execute(AddFirmwareTask.java:159)
        at com.ibm.datapower.amt.clientAPI.QueueProcessor.process(QueueProcessor.java:453)
        at com.ibm.datapower.amt.clientAPI.QueueProcessor.run(QueueProcessor.java:147)
        at java.lang.Thread.run(Thread.java:745)

**Comment by ghost** [comment]
Export CATALINA_OPTS=-Xmx3G on the environment before starting Tomee. The new firmwares are bigger and require more memory with the existing code. I didn't have time yet to see if there is a better way to process it without increasing the java heap.

**Comment by tomvanoppens** [comment]
just for the not linux minded people.
"Export CATALINA_OPTS=-Xmx3G" should be "export CATALINA_OPTS=-Xmx3G"

**Comment by tomvanoppens** [comment]
i get an error again .
it seems kind of everything starts haning for a while and then .. crash
https://dl.dropboxusercontent.com/u/12175340/error.txt

**Comment by ghost** [comment]
Hmm, I have not been able to recreate this issue. I can successfully add the IDG 7.2.0 firmware without any issues.
What JRE are you using?

**Comment by tomvanoppens** [comment]
The issue seems to persist even with idg7200.scrypt4

java version "1.7.0_85"
OpenJDK Runtime Environment (rhel-2.6.1.2.el7_1-x86_64 u85-b01)
OpenJDK 64-Bit Server VM (build 24.85-b03, mixed mode)

**Comment by ghost** [comment]
I have tested with the following JDK as well as with an IBM Java 1.8 JDK, neither gave me a problem with adding a firmware:

java version "1.7.0_79"
OpenJDK Runtime Environment (IcedTea 2.5.6) (7u79-2.5.6-0ubuntu1.14.04.1)
OpenJDK 64-Bit Server VM (build 24.79-b02, mixed mode)

Can you try again? Clear up all the entries from the logs directory and see what happens. What firmware are you trying to upload?

**Comment by ghost** [comment]
Any update?

**Comment by tomvanoppens** [comment]
it still fails.
I try to upload idg7200.scrypt4 it's about 463 MB
i tried with the IBM and OpenJDK
i also used remote upload and local upload (the file gets to the server in both cases i guess because when i used remote i could see the close come in )
